
server:
  port: 8763

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-peer3
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false
